version: "3"
services:
  fit-slam:
    image: fit-slam:22.04
    volumes:
      #full dev
      - /dev:/dev:rw
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #ros-workspaces
      - ./root_dir/:/root/:rw
      - ../.ros/:/root/.ros
      # orb slam3 workspaces
      # - ./ORB-SLAM3-ROS2-Docker/container_root/:/root/
      - ./ORB-SLAM3-ROS2-Docker/ORB_SLAM3/:/home/orb/ORB_SLAM3/
      - ./ORB-SLAM3-ROS2-Docker/traversability_mapping/:/home/traversability/traversability_mapping/
      - ./ORB-SLAM3-ROS2-Docker/orb_slam3_ros2_wrapper/:/root/colcon_ws/src/orb_slam3_ros2_wrapper/
      - ./ORB-SLAM3-ROS2-Docker/slam_msgs/:/root/colcon_ws/src/slam_msgs/
      - ./ORB-SLAM3-ROS2-Docker/traversability_mapping/traversability_ros_interface:/root/trav_ws/src/traversability_ros_interface
    env_file:
      - .env
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
    entrypoint: /bin/bash
