bt_exploration_node:
  ros__parameters:
    use_sim_time: True
    retry_count: 20
    nav2_goal_timeout_sec: 30 #secs
    # config: ["48.0", "60.0", "48.0", "1.25", "1.25", "1.25", "1.25", "60.0"]
    config: ["310.0", "260.0", "310.0", "-120.0", "-70.0", "-120.0", "-70.0", "260.0"]
    use_custom_sim: false
    # robot_namespaces: ['/scout_1', '/scout_2']
    robot_namespaces: ['/robot_0']
    # robot_namespaces: ['/scout_1', '/scout_2', '/scout_3']
    # robot_namespaces: ['/scout_1', '/scout_2', '/scout_3', '/scout_4']
    # robot_namespaces: ['/scout_1', '/scout_2', '/scout_3', '/scout_4', '/scout_5']
    min_frontier_cluster_size: 1
    max_frontier_cluster_size: 20
    max_frontier_distance: 50.0 # This should be equal to the parameter max_frontier_distance in frontier_roadmap_node
    frontier_match_xy_threshold: 1.0
    frontier_match_yaw_threshold: 0.40
    process_other_robots: true
    bt_xml_path: "/root/dev_ws/src/frontier_exploration/frontier_exploration/xml/exploration_with_fi.xml"

CostAssigner:
  ros__parameters:
    counter: 031150
    exploration_mode: ours
    
frontier_costs_manager_node:
  ros__parameters:
    alpha: 0.25 #set to 1.0 for maximum weight to arrival information and 0.0 for maximum weight to frontier path distance.
    beta: 1.0 #set to 1.0 for maximum weight to u1 and 0.0 for maximum weight to information on path.
    N_best_for_u2: 100000 #set to -1 for considering all the frontier for path computation (this will make the algorithm very time instensive!)
    planner_allow_unknown: true
    add_heading_cost: true
    vx_max: 0.5 # max linear speed of the robot. m/s (required if heading cost is added)
    wz_max: 0.5 # max angular speed of the robot. rad/s (required if heading cost is added)

localization_pose_sub_node:
  ros__parameters:
    exploration_mode: ours
    counter: 031150

frontier_roadmap_node:
  ros__parameters:
    max_frontier_distance: 25.1

explore_costmap:
  explore_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      resolution: 0.05
      robot_radius: 0.40
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer", "lethal_marker"]
      # plugins: ["static_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /robot_0/traversability_thresholded
        # map_topic: /simulation_costmap
        map_subscribe_transient_local: True
        enabled: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        inflation_radius: 0.30
        cost_scaling_factor: 6.0
        inflate_unknown: false
        inflate_around_unknown: false
      lethal_marker:
        plugin: "frontier_exploration/LethalMarker"
        enabled: True
      always_send_full_costmap: True

# goal_allocation_server:
#   ros__parameters:
    # robot_namespaces: ['/scout_1', '/scout_2']
    # robot_namespaces: ['']
