explore_client:
  ros__parameters:
    costmap_resolution: 0.05 # same as bounded_explore_layer
  
explore_server:
  ros__parameters:
    frequency: 15.0
    goal_aliasing: 2.0
    retry_count: 20
    nav2_goal_timeout_sec: 50 #secs
    use_traversability: true

polygon_point_publisher:
  ros__parameters:
    square_half_side_length: 15.0
    
frontier_selection_node:
  ros__parameters:
    exploration_mode: ours
    counter: 031150
    alpha: 0.26 #set to 1.0 for maximum weight to information and 0.0 for maximum weight to frontier path distance.
    beta: 0.49 #set to 1.0 for maximum weight to u1 and 0.0 for maximum weight to information on path.
    N_best_for_u2: 7 #set to -1 for considering all the frontier for path computation (this will make the algorithm very time instensive!)
    planner_allow_unknown: true
    frontier_detect_radius: 0.2

localization_pose_sub_node:
  ros__parameters:
    exploration_mode: ours
    counter: 031150

explore_costmap:
  explore_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "bounded_explore_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /traversability_thresholded
        map_subscribe_transient_local: True
      bounded_explore_layer:
        plugin: "frontier_exploration/BoundedExploreLayer"
        enabled: true
        resize_to_boundary: true
        frontier_travel_point: closest
        exploration_mode: ours
        explore_clear_space: false
        min_frontier_cluster_size: 1
        use_traversability: false
      always_send_full_costmap: false

goal_allocation_server:
  ros__parameters:
    robot_namespaces: ['scout_1', 'scout_2']
