explore_server:
  ros__parameters:
    retry_count: 20
    nav2_goal_timeout_sec: 5 #secs
    config: ["48.0", "60.0", "48.0", "1.25", "1.25", "1.25", "1.25", "60.0"]
    use_custom_sim: true
    # robot_namespaces: ['/scout_1', '/scout_2']
    # robot_namespaces: ['/scout_2']
    robot_namespaces: ['/scout_1', '/scout_2', '/scout_3']
    # robot_namespaces: ['/scout_1', '/scout_2', '/scout_3', '/scout_4']
    # robot_namespaces: ['/scout_1', '/scout_2', '/scout_3', '/scout_4', '/scout_5']
    min_frontier_cluster_size: 5
    max_frontier_cluster_size: 21
    frontier_match_xy_threshold: 1.0
    frontier_match_yaw_threshold: 0.40
    process_other_robots: false

bounded_explore_layer:
  ros__parameters:
    counter: 031150
    exploration_mode: ours
    
frontier_costs_manager_node:
  ros__parameters:
    alpha: 0.50 #set to 1.0 for maximum weight to arrival information and 0.0 for maximum weight to frontier path distance.
    beta: 0.50 #set to 1.0 for maximum weight to u1 and 0.0 for maximum weight to information on path.
    N_best_for_u2: 100000 #set to -1 for considering all the frontier for path computation (this will make the algorithm very time instensive!)
    planner_allow_unknown: true
    frontier_detect_radius: 0.0
    use_planning: false #if false, uses euclidean distance to frontier(cannot use FIMs to compute path information). If true, plans to the frontier.

localization_pose_sub_node:
  ros__parameters:
    exploration_mode: ours
    counter: 031150

explore_costmap:
  explore_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        # map_topic: /traversability_thresholded
        map_topic: /simulation_costmap
        map_subscribe_transient_local: True
        enabled: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: False
        inflation_radius: 0.50
        cost_scaling_factor: 6.0
        inflate_unknown: false
        inflate_around_unknown: false
      always_send_full_costmap: True

# goal_allocation_server:
#   ros__parameters:
    # robot_namespaces: ['/scout_1', '/scout_2']
    # robot_namespaces: ['']
