string robot_namespace
frontier_msgs/Frontier[] requested_frontier_list
frontier_msgs/Frontier[] prohibited_frontiers
---
bool success
frontier_msgs/Frontier[] frontier_list
float64[] frontier_costs
float64[] frontier_distances # the raw distance (plan / euclidean - depends on param)
float64[] frontier_arrival_information # no of unknown cells it will cover
float64[] frontier_path_information # amount of information it will gain