roadmap_explorer_node:
  ros__parameters:
    use_sim_time: False
    localisation_only_mode: False # false if in slam mode (mapping is active and you want the exploration to run on that)
    
    frontierSearch:
      min_frontier_cluster_size: 1.0
      max_frontier_cluster_size: 20.0
      frontier_search_distance: 25.0 # This should be equal to the parameter frontier_search_distance in frontier_roadmap_node
      lethal_threshold: 160 # >= is lethal, < is free space.
      max_frontier_search_distance: 140.0

    costCalculator:
      max_camera_depth: 2.0
      delta_theta: 0.10
      camera_fov: 1.04
      factor_of_max_is_min: 0.70
      closeness_rejection_threshold: 0.5
      planner_allow_unknown: true
      max_planning_distance_roadmap: 12.5

    costAssigner:
      cost_calculation_methods: ["RoadmapPlannerDistance", "ArrivalInformation"]

    frontierRoadmap:
      max_graph_reconstruction_distance: 10.0
      grid_cell_size: 1.0                           # Assuming each cell is 1x1 in size
      radius_to_decide_edges: 6.1                   # a node within this radius of another node is considered a child of the other node.
      min_distance_between_two_frontier_nodes: 0.25  # minimum distance between any node in the graph and the frontier node that will be added.
      min_distance_between_robot_pose_and_node: 0.25 # minimum distance between any nodes in the graph and the robot pose that is going to be added.

    fullPathOptimizer:
      num_frontiers_in_local_area: 5.0
      local_frontier_search_radius: 12.0
      add_yaw_to_tsp: false
      add_distance_to_robot_to_tsp: false 

    goalHysteresis:
      use_euclidean_distance: false
      use_roadmap_planner_distance: true

    explorationBT:
      bt_sleep_ms: 70
      exploration_boundary: [310.0, 260.0, 310.0, -120.0, -70.0, -120.0, -70.0, 260.0]
      abort_exploration_on_nav2_abort: false
      localisation_only_mode: false
      increment_search_distance_by: 35.0
      nav2_bt_xml: "/root/dev_ws/src/fit-slam2/fit_slam2/xml/active_slam_explore_to_pose.xml"
      bt_xml_path: "/root/dev_ws/src/fit-slam2/fit_slam2/xml/active_slam_exploration.xml"
    
    sensorSimulator:
      input_map_topic: "/map"
      input_map_is_transient_local: true
      explored_map_topic: "/explored_map"
      angular_resolution: 0.013
      sensor_update_rate: 1.0
      sensor_min_angle: -1.0
      sensor_max_angle: 1.0
      sensor_max_range: 1.5
    
    fisherInformation:
      fisher_information_threshold: 2.0

roadmap_explorer_costmap:
  roadmap_explorer_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: False
      resolution: 0.05
      robot_radius: 0.60
      track_unknown_space: true
      plugins: ["static_layer", "lethal_marker_exploration"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/traversability_thresholded"
        map_subscribe_transient_local: False
        enabled: True
      lethal_marker_exploration:
        plugin: "fit_slam2_nav2_plugins/LethalMarker"
        enabled: True
      always_send_full_costmap: True
